// ─── FraudShield PDF Export ───────────────────────────────────────────────────
// Uses jsPDF for layout + html2canvas for chart screenshots
// Single fraud report + session summary export

const PDF_COLORS = {
  bg:       [10, 13, 26],
  panel:    [17, 22, 39],
  border:   [30, 38, 64],
  accent:   [99, 102, 241],
  purple:   [139, 92, 246],
  success:  [16, 185, 129],
  danger:   [239, 68, 68],
  warning:  [245, 158, 11],
  text:     [226, 232, 240],
  text2:    [148, 163, 184],
  text3:    [71, 85, 105],
  white:    [255, 255, 255],
};

// ── Get current session ────────────────────────────────────────────────────────
function getSession() {
  try { return JSON.parse(sessionStorage.getItem('fraudshield_session') || '{}'); }
  catch(_) { return {}; }
}

// ── Helper: draw header block ─────────────────────────────────────────────────
function pdfHeader(doc, title, subtitle) {
  const W = doc.internal.pageSize.getWidth();

  // Dark background
  doc.setFillColor(...PDF_COLORS.bg);
  doc.rect(0, 0, W, 42, 'F');

  // Accent bar
  doc.setFillColor(...PDF_COLORS.accent);
  doc.rect(0, 0, 4, 42, 'F');

  // Logo + title
  doc.setTextColor(...PDF_COLORS.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('FraudShield', 14, 15);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...PDF_COLORS.text2);
  doc.text('FL + FZSL Intelligence System  ·  v4.0', 14, 22);

  // Report title (right)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...PDF_COLORS.white);
  doc.text(title, W - 14, 14, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...PDF_COLORS.text2);
  doc.text(subtitle, W - 14, 22, { align: 'right' });

  return 50; // next Y
}

// ── Helper: section title ─────────────────────────────────────────────────────
function pdfSection(doc, title, y) {
  const W = doc.internal.pageSize.getWidth();
  doc.setFillColor(...PDF_COLORS.panel);
  doc.roundedRect(10, y, W - 20, 9, 2, 2, 'F');
  doc.setFillColor(...PDF_COLORS.accent);
  doc.roundedRect(10, y, 3, 9, 1, 1, 'F');
  doc.setTextColor(...PDF_COLORS.text);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text(title.toUpperCase(), 17, y + 6.2);
  return y + 14;
}

// ── Helper: key-value row ─────────────────────────────────────────────────────
function pdfKV(doc, key, value, y, color) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...PDF_COLORS.text2);
  doc.text(key, 14, y);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...(color || PDF_COLORS.text));
  doc.text(String(value), 90, y);
  return y + 6.5;
}

// ── Helper: bullet line ───────────────────────────────────────────────────────
function pdfBullet(doc, text, y, W) {
  const clean = text.replace(/\*\*(.+?)\*\*/g, '$1').replace(/[📊🔵📋🟣✅💰🕐]/gu, '').trim();
  doc.setFillColor(...PDF_COLORS.accent);
  doc.circle(16, y - 1.5, 1, 'F');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...PDF_COLORS.text2);
  const lines = doc.splitTextToSize(clean, W - 30);
  doc.text(lines, 20, y);
  return y + lines.length * 5 + 2;
}

// ── Helper: page footer ───────────────────────────────────────────────────────
function pdfFooter(doc, pageNum, totalPages, session) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  doc.setDrawColor(...PDF_COLORS.border);
  doc.line(10, H - 15, W - 10, H - 15);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...PDF_COLORS.text3);
  doc.text(
    `FraudShield v4.0  ·  Generated by ${session.name || 'Unknown'} (${session.role || 'analyst'})  ·  ${new Date().toLocaleString('en-GB')}`,
    14, H - 9
  );
  doc.text(`Page ${pageNum} of ${totalPages}`, W - 14, H - 9, { align: 'right' });
}

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT 1: Single Fraud Transaction Report
// ─────────────────────────────────────────────────────────────────────────────
async function exportFraudReportPDF(txn) {
  if (!txn) { alert('No transaction data to export.'); return; }
  const session = getSession();
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: 'mm', format: 'a4', compress: true });
  const W = doc.internal.pageSize.getWidth();
  let y;

  // ── Page 1 ────────────────────────────────────────────────────────────────
  y = pdfHeader(doc, 'FRAUD INCIDENT REPORT', new Date().toLocaleDateString('en-GB', { year:'numeric', month:'long', day:'numeric' }));

  // Classification banner
  const isUnknown = txn.fraud_type === 'fraud_type_3';
  const bannerColor = isUnknown ? PDF_COLORS.purple : PDF_COLORS.danger;
  doc.setFillColor(...bannerColor);
  doc.roundedRect(10, y, W - 20, 14, 3, 3, 'F');
  doc.setTextColor(...PDF_COLORS.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(isUnknown ? '⚠  ZERO-SHOT — PREVIOUSLY UNSEEN FRAUD TYPE' : '  FRAUD TRANSACTION DETECTED', W / 2, y + 9, { align: 'center' });
  y += 20;

  // ── Section: Transaction Details ───────────────────────────────────────────
  y = pdfSection(doc, 'Transaction Details', y);
  const FRAUD_LABELS = {
    fraud_type_0: 'Type 0 — Card Cloning / CNP Fraud',
    fraud_type_1: 'Type 1 — Account Takeover (ATO)',
    fraud_type_2: 'Type 2 — Micro-Probing / Card Testing',
    fraud_type_3: 'Type 3 — Zero-Shot Detection (Unseen Pattern)',
  };
  y = pdfKV(doc, 'Transaction ID',  txn.id, y);
  y = pdfKV(doc, 'Timestamp',       new Date((txn.timestamp || Date.now() / 1000) * 1000).toLocaleString('en-GB'), y);
  y = pdfKV(doc, 'Amount',          `$${(txn.amount || 0).toFixed(2)}`, y, PDF_COLORS.danger);
  y = pdfKV(doc, 'Fraud Type',      FRAUD_LABELS[txn.fraud_type] || txn.fraud_type, y, isUnknown ? PDF_COLORS.purple : PDF_COLORS.danger);
  y = pdfKV(doc, 'Detection Method', isUnknown ? 'FZSL (Zero-Shot Learning)' : 'FL + FZSL', y);
  y += 4;

  // ── Section: Risk Scores ───────────────────────────────────────────────────
  y = pdfSection(doc, 'Risk Assessment', y);
  const flPct   = ((txn.fl_probability   || 0) * 100).toFixed(1);
  const fzslPct = ((txn.fzsl_fraud_probability || 0) * 100).toFixed(1);
  const confPct = ((txn.confidence || 0) * 100).toFixed(1);
  const hlevel  = txn.human_explanation?.risk_level || 'HIGH';
  const hlColor = hlevel.includes('CRITICAL') ? PDF_COLORS.danger : hlevel === 'HIGH' ? PDF_COLORS.warning : PDF_COLORS.text;
  y = pdfKV(doc, 'FL Probability',   `${flPct}%`,   y, flPct   > 80 ? PDF_COLORS.danger : PDF_COLORS.warning);
  y = pdfKV(doc, 'FZSL Score',       `${fzslPct}%`, y, fzslPct > 80 ? PDF_COLORS.danger : PDF_COLORS.warning);
  y = pdfKV(doc, 'Overall Confidence', `${confPct}%`, y);
  y = pdfKV(doc, 'Risk Level',       hlevel, y, hlColor);
  y = pdfKV(doc, 'Verdict',          txn.human_explanation?.verdict || 'FRAUD', y, PDF_COLORS.danger);
  y += 4;

  // ── Section: FZSL Similarity Scores ───────────────────────────────────────
  if (txn.similarity_scores && Object.keys(txn.similarity_scores).length > 0) {
    y = pdfSection(doc, 'FZSL Class Similarity Scores', y);
    const sorted = Object.entries(txn.similarity_scores).sort((a, b) => b[1] - a[1]);
    const BAR_W  = 60;
    for (const [cls, score] of sorted) {
      const label = FRAUD_LABELS[cls] || cls;
      const norm  = Math.max(0, (score + 1) / 2); // [-1,1] → [0,1]
      const barW  = norm * BAR_W;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...PDF_COLORS.text2);
      doc.text(label, 14, y);
      // Bar background
      doc.setFillColor(...PDF_COLORS.border);
      doc.roundedRect(W - 14 - BAR_W, y - 4, BAR_W, 5, 1, 1, 'F');
      // Bar fill
      const barColor = cls === 'normal' ? PDF_COLORS.success : cls === txn.fraud_type ? PDF_COLORS.danger : PDF_COLORS.text3;
      doc.setFillColor(...barColor);
      if (barW > 0) doc.roundedRect(W - 14 - BAR_W, y - 4, barW, 5, 1, 1, 'F');
      doc.setTextColor(...PDF_COLORS.text2);
      doc.text(score.toFixed(4), W - 14, y, { align: 'right' });
      y += 7.5;
    }
    y += 2;
  }

  // ── Section: SHAP Explanation ──────────────────────────────────────────────
  if (txn.shap_values && Object.keys(txn.shap_values).length > 0) {
    y = pdfSection(doc, 'SHAP Feature Importance (GradientExplainer)', y);
    const sorted = Object.entries(txn.shap_values)
      .sort((a, b) => Math.abs(b[1]) - Math.abs(a[1]))
      .slice(0, 10);
    const maxAbs = Math.max(...sorted.map(([, v]) => Math.abs(v)), 0.001);
    const BAR_W  = 50;

    for (const [feat, val] of sorted) {
      const norm   = Math.abs(val) / maxAbs;
      const barW   = norm * BAR_W;
      const isPos  = val > 0;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(...PDF_COLORS.text);
      doc.text(feat, 14, y);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(...PDF_COLORS.text3);
      doc.text(`${isPos ? '+' : ''}${val.toFixed(4)}`, 50, y);
      // Bar bg
      doc.setFillColor(...PDF_COLORS.border);
      doc.roundedRect(70, y - 4, BAR_W, 5, 1, 1, 'F');
      // Bar fill
      doc.setFillColor(...(isPos ? PDF_COLORS.danger : PDF_COLORS.accent));
      if (barW > 0) doc.roundedRect(70, y - 4, barW, 5, 1, 1, 'F');
      doc.setTextColor(isPos ? 239 : 99, isPos ? 68 : 102, isPos ? 68 : 241);
      doc.setFontSize(7.5);
      doc.text(isPos ? '▲ Fraud ↑' : '▼ Reduces', 125, y);
      y += 7.5;
    }
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7);
    doc.setTextColor(...PDF_COLORS.text3);
    doc.text('SHAP computed via GradientExplainer (gradient × input). Red = increases fraud probability.', 14, y + 2);
    y += 10;
  }

  // ── SHAP source note ───────────────────────────────────────────────────────
  if (y < 200 && txn.human_explanation?.bullets?.length > 0) {
    // ── Section: AI Explanation ──────────────────────────────────────────────
    y = pdfSection(doc, 'AI-Generated Risk Narrative', y);
    for (const bullet of (txn.human_explanation.bullets || []).slice(0, 6)) {
      if (y > 255) break;
      y = pdfBullet(doc, bullet, y, W);
    }
    y += 4;
  }

  // ── Page footer ────────────────────────────────────────────────────────────
  pdfFooter(doc, 1, 2, session);

  // ── Page 2: Compliance ────────────────────────────────────────────────────
  doc.addPage();
  y = pdfHeader(doc, 'COMPLIANCE & PRIVACY REPORT', `Transaction ${txn.id}`);

  // ── Section: Differential Privacy ─────────────────────────────────────────
  y = pdfSection(doc, 'Differential Privacy Compliance (GDPR)', y);
  y = pdfKV(doc, 'Mechanism',         'Gaussian Mechanism', y);
  y = pdfKV(doc, 'Privacy Guarantee', '(ε, δ)-Differential Privacy', y, PDF_COLORS.accent);
  y = pdfKV(doc, 'Epsilon (ε)',        'Budget tracked per FL round', y);
  y = pdfKV(doc, 'Delta (δ)',          '1.0 × 10⁻⁵', y);
  y = pdfKV(doc, 'Noise Formula',      'ε = √(2·ln(1.25/δ)) · Δf / σ', y);
  y = pdfKV(doc, 'FL Architecture',   'FedAvg — raw data never leaves client', y, PDF_COLORS.success);
  y = pdfKV(doc, 'GDPR Compliance',   '✓ Article 25 — Privacy by Design', y, PDF_COLORS.success);
  y += 6;

  // ── Section: Federated Learning Info ─────────────────────────────────────
  y = pdfSection(doc, 'Federated Learning Architecture', y);
  y = pdfKV(doc, 'Algorithm',     'FedAvg (McMahan et al., 2017)', y);
  y = pdfKV(doc, 'Clients',       '4 bank clients (Bank A–D)', y);
  y = pdfKV(doc, 'Data sharing',  'Model weights only — no raw data', y, PDF_COLORS.success);
  y = pdfKV(doc, 'Global F1',     '96.47% (FL + FZSL)', y, PDF_COLORS.success);
  y = pdfKV(doc, 'Zero-Shot',     '98.3% unseen fraud detection', y, PDF_COLORS.accent);
  y += 6;

  // ── Section: Analyst Signature ────────────────────────────────────────────
  y = pdfSection(doc, 'Analyst Information', y);
  y = pdfKV(doc, 'Analyst Name',  session.name  || 'Unknown', y);
  y = pdfKV(doc, 'Role',          session.title || session.role || 'Analyst', y);
  y = pdfKV(doc, 'Report Date',   new Date().toLocaleString('en-GB'), y);
  y = pdfKV(doc, 'System',        'FraudShield v4.0 — FL + FZSL Intelligence System', y);
  y += 12;

  // Signature box
  doc.setDrawColor(...PDF_COLORS.border);
  doc.roundedRect(14, y, 80, 20, 2, 2);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...PDF_COLORS.text3);
  doc.text('Analyst Signature', 18, y + 16);

  doc.setDrawColor(...PDF_COLORS.border);
  doc.roundedRect(W - 94, y, 80, 20, 2, 2);
  doc.text('Supervisor Signature', W - 90, y + 16);
  y += 28;

  // ── Disclaimer ────────────────────────────────────────────────────────────
  doc.setFillColor(30, 38, 64);
  doc.roundedRect(10, y, W - 20, 28, 3, 3, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...PDF_COLORS.text2);
  doc.text('DISCLAIMER', 16, y + 8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...PDF_COLORS.text3);
  const disclaimer = 'This report was generated automatically by the FraudShield AI system. Fraud classifications are based on Federated Learning (FL) and Fuzzy Zero-Shot Learning (FZSL) models trained on the ULB Credit Card Fraud Detection dataset. All decisions should be reviewed by a qualified fraud analyst before taking action. This system complies with GDPR Article 25 (Privacy by Design) through differential privacy gradient protection.';
  const dLines = doc.splitTextToSize(disclaimer, W - 34);
  doc.text(dLines, 16, y + 15);

  pdfFooter(doc, 2, 2, session);

  // ── Save ──────────────────────────────────────────────────────────────────
  const filename = `FraudShield_Report_${txn.id}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT 2: Session Summary (all fraud alerts)
// ─────────────────────────────────────────────────────────────────────────────
async function exportSessionPDF() {
  const session = getSession();
  const alerts  = window._sessionAlerts || [];
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: 'mm', format: 'a4', compress: true });
  const W = doc.internal.pageSize.getWidth();
  let y;

  y = pdfHeader(doc, 'SESSION FRAUD SUMMARY', `${alerts.length} fraud events detected`);

  // Session info bar
  doc.setFillColor(...PDF_COLORS.panel);
  doc.roundedRect(10, y, W - 20, 14, 2, 2, 'F');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...PDF_COLORS.text2);
  doc.text(`Analyst: ${session.name || 'Unknown'}  ·  Role: ${session.title || session.role}  ·  Session started: ${session.loginTime ? new Date(session.loginTime).toLocaleString('en-GB') : '—'}`, 16, y + 9);
  y += 20;

  if (alerts.length === 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(...PDF_COLORS.text3);
    doc.text('No fraud events were detected in this session.', W / 2, y + 20, { align: 'center' });
  } else {
    // ── Summary stats ────────────────────────────────────────────────────────
    y = pdfSection(doc, 'Session Statistics', y);
    const totalFraud = alerts.length;
    const zsl  = alerts.filter(a => a.fraud_type === 'fraud_type_3').length;
    const avgAmt = alerts.reduce((s, a) => s + (a.amount || 0), 0) / totalFraud;
    const totalAmt = alerts.reduce((s, a) => s + (a.amount || 0), 0);
    y = pdfKV(doc, 'Total Fraud Events',      totalFraud, y, PDF_COLORS.danger);
    y = pdfKV(doc, 'Zero-Shot (New Type)',     zsl, y, PDF_COLORS.purple);
    y = pdfKV(doc, 'Total Blocked Amount',     `$${totalAmt.toFixed(2)}`, y, PDF_COLORS.danger);
    y = pdfKV(doc, 'Average Fraud Amount',     `$${avgAmt.toFixed(2)}`, y);
    y = pdfKV(doc, 'Report Generated',         new Date().toLocaleString('en-GB'), y);
    y += 4;

    // ── Alert table ───────────────────────────────────────────────────────────
    y = pdfSection(doc, 'Fraud Event Log', y);
    const FRAUD_SHORT = { fraud_type_0:'Type 0', fraud_type_1:'Type 1', fraud_type_2:'Type 2', fraud_type_3:'ZSL ⚡' };
    const COL = [14, 52, 85, 120, 150, 175];
    const HDRS = ['Transaction ID', 'Time', 'Amount', 'Type', 'FL %', 'Risk'];

    // Table header
    doc.setFillColor(...PDF_COLORS.accent);
    doc.roundedRect(10, y, W - 20, 7, 1, 1, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(...PDF_COLORS.white);
    HDRS.forEach((h, i) => doc.text(h, COL[i], y + 5));
    y += 10;

    // Table rows
    for (let i = 0; i < Math.min(alerts.length, 25); i++) {
      const a = alerts[i];
      if (y > 265) {
        pdfFooter(doc, doc.getNumberOfPages(), '?', session);
        doc.addPage();
        y = 20;
      }
      doc.setFillColor(i % 2 === 0 ? 17 : 13, i % 2 === 0 ? 22 : 18, i % 2 === 0 ? 39 : 30);
      doc.roundedRect(10, y - 3, W - 20, 7, 1, 1, 'F');
      doc.setFont('helvetica', a.fraud_type === 'fraud_type_3' ? 'bold' : 'normal');
      doc.setFontSize(7.5);
      const rowColor = a.fraud_type === 'fraud_type_3' ? PDF_COLORS.purple : PDF_COLORS.text2;
      doc.setTextColor(...rowColor);
      doc.text(a.id || '—', COL[0], y + 2);
      doc.text(a.timestamp ? new Date(a.timestamp * 1000).toLocaleTimeString('en-GB') : '—', COL[1], y + 2);
      doc.text(`$${(a.amount || 0).toFixed(2)}`, COL[2], y + 2);
      doc.text(FRAUD_SHORT[a.fraud_type] || a.fraud_type, COL[3], y + 2);
      doc.text(`${((a.fl_probability || 0) * 100).toFixed(1)}%`, COL[4], y + 2);
      doc.text(a.human_explanation?.risk_level?.split(' ')[0] || 'HIGH', COL[5], y + 2);
      y += 7;
    }
    if (alerts.length > 25) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(7.5);
      doc.setTextColor(...PDF_COLORS.text3);
      doc.text(`... and ${alerts.length - 25} more events (export individual reports for full detail)`, 14, y + 4);
    }
  }

  pdfFooter(doc, doc.getNumberOfPages(), doc.getNumberOfPages(), session);
  const filename = `FraudShield_Session_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}

// ─────────────────────────────────────────────────────────────────────────────
// INIT: called from app.js on DOMContentLoaded
// ─────────────────────────────────────────────────────────────────────────────
window._sessionAlerts = [];

function initAuthUI() {
  const session = getSession();
  if (!session.role) return;

  // Fill user bar
  const roleBadge = document.getElementById('user-role-badge');
  const userName  = document.getElementById('user-name');
  const userTitle = document.getElementById('user-title');
  const btnReset  = document.getElementById('btn-reset');
  const btnFraud  = document.getElementById('btn-new-fraud');
  const btnFL     = document.getElementById('btn-fl-round');

  if (roleBadge) {
    roleBadge.textContent = session.role.charAt(0).toUpperCase() + session.role.slice(1);
    roleBadge.setAttribute('data-role', session.role);
  }
  if (userName)  userName.textContent  = session.name  || 'User';
  if (userTitle) userTitle.textContent = session.title || session.role;

  const perms = session.permissions || {};

  // Role-based UI gating
  if (!perms.canReset   && btnReset) { btnReset.style.display = 'none'; }
  if (!perms.canTriggerFraud && btnFraud) { btnFraud.style.display = 'none'; }
  if (!perms.canRunFL   && btnFL)   { btnFL.disabled = true; btnFL.title = 'Admin access required'; btnFL.style.opacity = '0.4'; }

  // Auditor: hide live feed write actions, show audit emphasis
  if (session.role === 'auditor') {
    const flPanel = document.querySelector('.panel-fl');
    if (flPanel) flPanel.style.opacity = '0.6';
  }
}

function logout() {
  sessionStorage.removeItem('fraudshield_session');
  window.location.replace('login.html');
}

// Auto-init
document.addEventListener('DOMContentLoaded', () => {
  initAuthUI();
});
